/* eslint-disable @next/next/no-img-element */
import { Tabs, TabList, TabPanels, Tab, TabPanel } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import {
  DeviceComponent,
  LineTokenComponent,
  NotificationComponent,
} from "../components";

const SetUpPage = () => {
  return (
    <>
      <Head>
        <title>{process.env.APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full h-full">
        <div className="container mx-auto px-6 mt-4">
          <div className="w-full">
            <Tabs align="end" variant="enclosed">
              <TabList>
                <Tab>ตั้งค่าอุปกรณ์</Tab>
                <Tab>ตั้งค่า Line Token</Tab>
                <Tab>ตั้งค่าการแจ้งเตือน</Tab>
              </TabList>
              <TabPanels>
                <TabPanel>
                  <DeviceComponent />
                </TabPanel>
                <TabPanel>
                  <LineTokenComponent />
                </TabPanel>
                <TabPanel>
                  <NotificationComponent />
                </TabPanel>
              </TabPanels>
            </Tabs>
          </div>
        </div>
      </div>
    </>
  );
};

export default SetUpPage;
