import Head from "next/head";
import { useEffect } from "react";
import { useState } from "react";

const HomePage = () => {
  const [data, setData] = useState([]);

  const FetchData = async () => {
    var requestOptions = {
      method: "GET",
      redirect: "follow",
    };

    const res = await fetch(
      `${process.env.API_HOST}/api/v1/temp`,
      requestOptions
    );
    if (res.ok) {
      const r = await res.json();
      setData(r.data);
      console.dir(r.data);
    }
  };

  useEffect(() => {
    FetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="overflow-x-auto">
          <table className="table w-full table-compact">
            <thead>
              <tr>
                <th>#</th>
                <th>Device</th>
                <th>Temp</th>
                <th>Humidity</th>
                <th>Status</th>
                <th>LastUpdated</th>
              </tr>
            </thead>
            <tbody>
              {data?.map((i, x) => (
                <tr key={i.id}>
                  <th>{x + 1}</th>
                  <td>{i.device.name}</td>
                  <td>{i.temp}</td>
                  <td>{i.humidity}</td>
                  <td>
                    {i.temp >= i.device.alert_on ? (
                      <span className="text-rose-800">H</span>
                    ) : (
                      <span className="text-green-800">L</span>
                    )}
                  </td>
                  <td>{i.on_date_time}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default HomePage;
